2.2 Высота дерева
---
Вычислить высоту данного дерева.
Вход. Корневое дерево с вершинами {0..n-1}, заданное
как последовательность paren_t_0; : : : ; paren_t_n−1, где parent_i —
родитель i-й вершины.
Выход. Высота дерева
=-=
Формат входа. Первая строка содержит натуральное число n. Вторая
строка содержит n целых чисел parent0; : : : ; parentn−1. 
Для каждого 0 ≤ i ≤ n−1, parenti — родитель вершины i; если parenti = −1, то i является корнем. 
Гарантируется, что корень ровно один. Гарантируется, что данная последовательность задаёт дерево.
Формат выхода. Высота дерева.
Ограничения. 1 ≤ n ≤ 10^5
-=-
Пример.
Вход:
5
4 -1 4 1 1
Выход:
3
-=
Вход:
5
-1 0 4 0 3
Выход:
4
-=



In [1]:
#Failed test 7 of 28. Time limit exceeded

import sys

sys.setrecursionlimit(20000)

n=input()
s=input()
t=[]

for i in s.split():
    t.append(int(i))

def heigh(n): 
    length=1
    v=t[n]
    if v==-1:
 #       print("+",length)
        return length
    else:
        return length+heigh(v)

#print(t)
max=0
for index,i in enumerate(t):
    h=heigh(index)
    if h>max:
        max = h
    #print(index,heigh(index))
print(max)

5
4 -1 4 1 1
3


In [ ]:
#5 4 -1 4 1 1

import sys

sys.setrecursionlimit(20000)

n=input()
s=input()
t=[]

for i in s.split():
    t.append(int(i))

def heigh(n): 
    length=1
    v=t[n]
    if v==-1:
 #       print("+",length)
        return length
    else:
        return length+heigh(v)

#print(t)
max=0
for index,i in enumerate(t):
    h=heigh(index)
    if h>max:
        max = h
    #print(index,heigh(index))
print(max)

In [ ]:
test
---
num = 10 ** 6
tree = [i+1 for i in range(num-1)] + [-1]

print(num)
print(*tree)

print()

tree = [i - 1 for i in range(10 ** 6)]
print(num)
print(*tree)

In [14]:
# Works!!!!!!!
import sys

sys.setrecursionlimit(20000)

n=input()
s=input()
t=[]

for i in s.split(): 
    g = int(i)
    #print(g)
    #print(g not in t)
    #if g not in t:
    t.append(g)
h={}
def heigh(n): 
    length=1
    result=1
    v=t[n]
    print("v",v)    
    if v==-1:        
        return length
    else:
        print("h1",h)
        if h.get(v):
            result = h[v]
            return result
        else:
            result=heigh(v)        
        #if not h.get(v):    
            #h[v] = result  
        print("result",result)
        print("h2",h)           
        print("t.index(v)",t.index(v))
        return length+result
#9 7 5 5 2 9 9 9 2 -1
print(t)


for index,i in enumerate(t):
    print("index,i",index,i)
    if not h.get(i):
#        if i==-1:
     #       h[i] = 1
     #   else:
    #        h[i] = 
        h[i] = heigh(index)
        print("_h",h)

#max=0        
#for i in h.values():    
    #if i>max:    
        #max = i
print(h)
m=max(h.values())
print(m)

10
9 7 5 5 2 9 9 9 2 -1
[9, 7, 5, 5, 2, 9, 9, 9, 2, -1]
index,i 0 9
v 9
h1 {}
v -1
result 1
h2 {}
t.index(v) 0
_h {9: 2}
index,i 1 7
v 7
h1 {9: 2}
v 9
h1 {9: 2}
result 2
h2 {9: 2}
t.index(v) 1
_h {9: 2, 7: 3}
index,i 2 5
v 5
h1 {9: 2, 7: 3}
v 9
h1 {9: 2, 7: 3}
result 2
h2 {9: 2, 7: 3}
t.index(v) 2
_h {9: 2, 7: 3, 5: 3}
index,i 3 5
index,i 4 2
v 2
h1 {9: 2, 7: 3, 5: 3}
v 5
h1 {9: 2, 7: 3, 5: 3}
result 3
h2 {9: 2, 7: 3, 5: 3}
t.index(v) 4
_h {9: 2, 7: 3, 5: 3, 2: 4}
index,i 5 9
index,i 6 9
index,i 7 9
index,i 8 2
index,i 9 -1
v -1
_h {9: 2, 7: 3, 5: 3, 2: 4, -1: 1}
{9: 2, 7: 3, 5: 3, 2: 4, -1: 1}
4


In [ ]:
https://stepik.org/lesson/41234/step/2?discussion=592911&unit=19818
    Решил через ленивую динамику. Создал список length размера n и заполнил его значениями -1. 
    В самой же рекурсии вначале проверял значение в ячейке length[i]. 
    Если оно равно -1, то проходил рекурсией и изменял -1 на высоту дерева для этого элемента массива, 
    иначе сразу возвращал значение из этой ячейки.
    
Test input:
10
9 7 5 5 2 9 9 9 2 -1

Correct output:
4

;
====================

2.3.Симуляция обработки сетевых пакетов
---
Реализовать обработчик сетевых пакетов.
Вход. Размер буфера size и число пакетов n, а также две последовательности arrival_1,...,arrival_n и
duration_1,...,duration_n, обозначающих время поступления и длительность обработки n пакетов.

Выход. Для каждого из данных n пакетов необходимо
вывести время начала его обработки или −1, если пакет
не был обработан (это происходит в случае, когда пакет
поступает в момент, когда в буфере компьютера уже
находится size пакетов)

In [ ]:
Формат входа. Первая строка входа содержит размер буфера size и
число пакетов n. Каждая из следующих n строк содержит два
числа: время arrival_i прибытия i-го пакета и время duration_i,
необходимое на его обработку. Гарантируется, что arrival_1 ≤
arrival_2 ≤ · · · ≤ arrival_n. При этом может оказаться, что
arrival_i−1 = arrival_i. В таком случае считаем, что пакет i − 1 поступил раньше пакета i.

Формат выхода. Для каждого из n пакетов выведите время, когда
процессор начал его обрабатывать, или −1, если пакет был отброшен.
Ограничения. Все числа во входе целые. 1 ≤ size ≤ 10^5; 0 ≤ n ≤ 10^5;
0 ≤ arrivali ≤ 10^6; 0 ≤ durationi ≤ 10^3; arrivali ≤ arrivali+1 для всех
1 ≤ i ≤ n − 1.


Пример.
Вход:
1 0
Выход:
Если пакетов нет, выводить ничего не нужно.


Пример.
Вход:
1 1
0 0
Выход:
0
Пакет поступил в момент времени 0, и компьютер тут же начал
его обрабатывать.


Пример.
Вход:
1 2
0 1
0 1
Выход:
0
-1
Первый пакет поступил в момент времени 0, второй пакет поступил также в момент времени 0, но был отброшен, поскольку буфер в этот момент полностью заполнен (первым пакетом).
Первый пакет начал обрабатываться в момент времени 0, второй был отброшен.


Пример.
Вход:
1 2
0 1
1 1
Выход:
0
1

In [25]:
#import queue
from collections import deque

s = input()
size = int(s.split()[0])
n = int(s.split()[1])
arrival=[]
duration=[]
buf=[-1 for i in range(n)]

for i in range(n):
    s = input()
    arrival.append(int(s.split()[0]))
    duration.append(int(s.split()[1]))
#print(arrival)
#print(duration)
#while len()    
 #   for i in range(n):
  #      if arrival[i]=i
   # buf.append()

#result=[]   
d = deque(buf, size)
#q = queue.Queue(n)
        #try:
           # q.put(j)            
       # except queue.Full
           # print("-1 queue.Full",queue.Full)    
#print("d",d)    
if n>0:
    for i,j in zip(arrival, duration):
        #k=0
        #while k<=size-1 and d[k]>=0 and d[k]<i:
            #d.popleft()
            #k+=1
        #if i>d[-1]:
        if d[0]<=i:
            d.popleft()
            d.append(i+j)  
            print(i)
        else:
            print("-1")    



2 6
0 2
0 0
2 0
3 0
4 0
5 0
[0, 0, 2, 3, 4, 5]
[2, 0, 0, 0, 0, 0]
0
2
2
5
6
7


In [ ]:
https://stepik.org/lesson/41234/step/3?discussion=384057&unit=19818
    Решил без использования классов.
Используем очередь фиксированного размера, в которой храним для пакетов, попавших в буфер, 
время, когда процессор освободится и сможет перейти к обработке следующего пакета.
Очередь хранит целые числа в порядке возрастания.
Получая очередной пакет, сравниваем его время получения с первым элементом очереди, 
если оно меньше, то выводим -1. Т.к. процессор в этот момент будет занят и пакет в буфер не попадет.
Если больше или равно, значит первый элемент очереди к моменту получения пакета будет уже обработан 
и покинет буфер и пакет сам сможет в буфер попасть. 
Удаляем первый элемент очереди, вычисляем время исполнения пакета и добавляем его в конец очереди.

На Питоне 3 решение уместилось в 17 строк.

In [ ]:
3 6
0 7
0 0
2 0
3 3
4 0
5 0

вывод: 0 7 7 -1 -1 -1
#mine
0
0
2
-1
-1
-1

In [ ]:
2 6
0 2
0 0
2 0
3 0
4 0
5 0

вывод: 0 2 2 3 4 5

#mine
0
0
2
3
4
5

In [ ]:
#Failed test 12 of 22. Wrong answer
import queue
from collections import deque

s = input()
size = int(s.split()[0])
n = int(s.split()[1])
arrival=[]
duration=[]
buf=[-1 for i in range(n)]

for i in range(n):
    s = input()
    arrival.append(int(s.split()[0]))
    duration.append(int(s.split()[1]))
print(arrival)
print(duration)
#while len()    
 #   for i in range(n):
  #      if arrival[i]=i
   # buf.append()

result=[]   
d = deque(buf, size)
q = queue.Queue(n)
        #try:
           # q.put(j)            
       # except queue.Full
           # print("-1 queue.Full",queue.Full)    
#print("d",d)    
out=0
if n>0:
    a=0
    delay=0
    for i,j in zip(arrival, duration):
        #k=0
        #while k<=size-1 and d[k]>=0 and d[k]<i:
            #d.popleft()
            #k+=1
        #if i>d[-1]:
        if d[0]<=i:            
            d.popleft()
            d.append(i+j)
            #print(i+a)
            #delay =
            
            if i<=a:
                out=a
            else:
                out=i+a#+delay)
            print(out)
            #a+=j
            if i<=out:   #?
                a+=j
            else:
                a=0#????
        else:
            print("-1")        

#for i in q.queue:
    #print(i)

In [38]:
#
import queue
from collections import deque

s = input()
size = int(s.split()[0])
n = int(s.split()[1])
arrival=[]
duration=[]
buf=[-1 for i in range(n)]

for i in range(n):
    s = input()
    arrival.append(int(s.split()[0]))
    duration.append(int(s.split()[1]))
print(arrival)
print(duration)
#while len()    
 #   for i in range(n):
  #      if arrival[i]=i
   # buf.append()

result=[]   
d = deque(buf, size)
q = queue.Queue(n)
        #try:
           # q.put(j)            
       # except queue.Full
           # print("-1 queue.Full",queue.Full)    
#print("d",d)    

if n>0:
    last=0
    a=0
    delay=0
    for i,j in zip(arrival, duration):

        if i>=d[0]:            
            d.popleft()
            d.append(i+j)           
            #if i<=last: #=?   
                #delay+=j
           # else:
               # delay=j           
             #last=i+delay
            print(i+delay) 
            if i<last: #=?
                #
                #print(delay)                
                last=delay
                delay+=j
            else:                 
                last=i+delay
                delay=j
                #print(last) 
            #print(last) 
            
          
        else:
            print("-1")    

3 6
0 7
0 0
2 0
3 3
4 0
5 0
[0, 0, 2, 3, 4, 5]
[7, 0, 0, 3, 0, 0]
0
7
2
-1
-1
-1


In [ ]:
2 6

0 2
0 0
2 0
3 0
4 0
5 0
вывод: 0 2 2 3 4 5

3 6
0 7
0 0
2 0
3 3
4 0
5 0

вывод: 0 7 7 -1 -1 -1

In [49]:
#Failed test #17 of 22. Wrong answer
import queue
from collections import deque

s = input()
size = int(s.split()[0])
n = int(s.split()[1])
arrival=[]
duration=[]
buf=[-1 for i in range(n)]

for i in range(n):
    s = input()
    arrival.append(int(s.split()[0]))
    duration.append(int(s.split()[1]))
print(arrival)
print(duration)
d = deque(buf, size)
if n>0:
    last=0
    a=0
    delay=0
    for i,j in zip(arrival, duration):

        if i>=d[0]:            
            d.popleft()
            d.append(i+j)
            if i<delay:
                last=delay
                delay=j+delay                
            else:                
                #print(i+delay)
                delay=j
                last=i#+j
            print(last)
            """print(i+last)
            last=i+last
            if i<last: 
                last=delay
                delay+=j
            else:                 
                last=i+delay
                delay=j       """
        else:
            print("-1")    

2 5
2 9
4 8
10 9
15 2
19 1
[2, 4, 10, 15, 19]
[9, 8, 9, 2, 1]
2
9
-1
17
19


In [ ]:
2 6
0 2
0 0
2 0
3 0
4 0
5 0
вывод: 0 2 2 3 4 5

3 6
0 7
0 0
2 0
3 3
4 0
5 0
вывод: 0 7 7 -1 -1 -1
    
2 5
2 9
4 8
10 9
15 2
19 1
Ответ:
2 11 -1 19 21    

In [2]:
#Failed test #17 of 22. Wrong answer
import queue
from collections import deque

s = input()
size = int(s.split()[0])
n = int(s.split()[1])
arrival=[]
duration=[]
buf=[-1 for i in range(n)]

for i in range(n):
    s = input()
    arrival.append(int(s.split()[0]))
    duration.append(int(s.split()[1]))
print(arrival)
print(duration)
d = deque(buf, size)
if n>0:
    last=0
    a=0
    delay=0#
    delay=arrival[0]
    for i,j in zip(arrival, duration):
        print(i,j)
        print(d)
        if i>=d[0]:            
        #if i>=(d[0]+arrival[0]):            
            d.popleft()
            d.append(i+j)#(j)
            if i<delay:
                last=delay
                delay=j+delay  #+i 
                #delay=i+delay
            else:                
                #print(i+delay)
                last=i
                delay=j  +i#              
            """last=delay                
            delay=j+delay""" 
            print(last, "delay=",delay)
            """print(i+last)
            last=i+last
            if i<last: 
                last=delay
                delay+=j
            else:                 
                last=i+delay
                delay=j       """
        else:
            print("-1")    

3 8
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7, 8]
1 1
deque([-1, -1, -1], maxlen=3)
1 delay= 2
2 2
deque([-1, -1, 2], maxlen=3)
2 delay= 4
3 3
deque([-1, 2, 4], maxlen=3)
4 delay= 7
4 4
deque([2, 4, 6], maxlen=3)
7 delay= 11
5 5
deque([4, 6, 8], maxlen=3)
11 delay= 16
6 6
deque([6, 8, 10], maxlen=3)
16 delay= 22
7 7
deque([8, 10, 12], maxlen=3)
-1
8 8
deque([8, 10, 12], maxlen=3)
22 delay= 30


In [ ]:
3 8
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8

Ответ: 1 2 4 7 11 -1 16 -1

1 5
999999 1
1000000 0
1000000 1
1000000 0
1000000 0

Ответ: 999999 1000000 1000000 -1 -1
\\\\\\
999999 1
deque([-1], maxlen=1)
999999 delay= 1000000
1000000 0
deque([1000000], maxlen=1)
1000000 delay= 1000000
1000000 1
deque([1000000], maxlen=1)
1000000 delay= 1000001
1000000 0
deque([1000001], maxlen=1)
-1
1000000 0
deque([1000001], maxlen=1)
-1
\\\\\\

2 6
0 2
0 0
2 0
3 0
4 0
5 0
вывод: 0 2 2 3 4 5

3 6
0 7
0 0
2 0
3 3
4 0
5 0
вывод: 0 7 7 -1 -1 -1

2 5
2 9
4 8
10 9
15 2
19 1
Ответ:
2 11 -1 19 21    

In [3]:
#WOOORRKKSS!
import queue
from collections import deque

s = input()
size = int(s.split()[0])
n = int(s.split()[1])
arrival=[]
duration=[]
buf=[-1 for i in range(n)]

for i in range(n):
    s = input()
    arrival.append(int(s.split()[0]))
    duration.append(int(s.split()[1]))
print(arrival)
print(duration)
d = deque(buf, size)
if n>0:
    last=0
    a=0
    delay=0#
    delay=arrival[0]
    for i,j in zip(arrival, duration):
        print(i,j)
        print(d)
        if i>=d[0]:            
        #if i>=(d[0]+arrival[0]):            
            d.popleft()
            d.append(delay+j)#(j)
            if i<delay:
                last=delay
                delay=j+delay  #+i 
                #delay=i+delay
            else:                
                #print(i+delay)
                last=i
                delay=j  +i#              
            """last=delay                
            delay=j+delay""" 
            print(last, "delay=",delay)
            """print(i+last)
            last=i+last
            if i<last: 
                last=delay
                delay+=j
            else:                 
                last=i+delay
                delay=j       """
        else:
            print("-1")   

2 5
2 9
4 8
10 9
15 2
19 1
[2, 4, 10, 15, 19]
[9, 8, 9, 2, 1]
2 9
deque([-1, -1], maxlen=2)
2 delay= 11
4 8
deque([-1, 11], maxlen=2)
11 delay= 19
10 9
deque([11, 19], maxlen=2)
-1
15 2
deque([11, 19], maxlen=2)
19 delay= 21
19 1
deque([19, 21], maxlen=2)
21 delay= 22


Стек с поддержкой максимума
--
Реализовать стек с поддержкой операций push, pop и max.
Вход. Последовательность запросов push, pop и max .
Выход. Для каждого запроса max вывести максимальное
число, находящееся на стеке.
-=-
Формат входа. Первая строка содержит число запросов q. Каждая из
последующих q строк задаёт запрос в одном из следующих форматов: push v, pop, or max.
Формат выхода. Для каждого запроса max выведите (в отдельной
строке) текущий максимум на стеке.
Ограничения. 1 ≤ q ≤ 400 000, 0 ≤ v ≤ 100 000.
-=-
Пример.
Вход:
3
push 1
push 7
pop
Выход:
Выход пуст, потому что нет max запросов.

Пример.
Вход:
5
push 2
push 1
max
pop
max
Выход:
22

Пример.
Вход:
6
push 7
push 1
push 7
max
pop
max
Выход:
77

Пример.
Вход:
5
push 1
push 2
max
pop
max
Выход:
21

Пример.
Вход:
10
push 2
push 3
push 9
push 7
push 2
max
max
max
pop
max
Выход:
9999

In [7]:
#from collections import deque

n = int(input())

stack = []
m = []
flag = True
#buf=[-1 for i in range(n)]
#d = deque(n)
for i in range(n):
    s = input().split()
    if s[0]=='pop':
        if stack:
            t=stack.pop()
            if t==m[-1]:
                m.pop()
    elif s[0]=='push':
        j = int(s[1])
        stack.append(int(s[1]))
        if flag:
            m.append(j)
            flag = False
        else:
            if j>=m[-1]:
                m.append(j)
    elif s[0]=='max':
        print(m[-1])




5
push 2
push 1
max
2
max
2
max
2


2.5 Максимум в скользящем окне
--
Максимум в скользящем окне
Найти максимум в каждом окне размера m данного массива чисел
A[1 : : : n].
Вход. Массив чисел A[1 : : : n] и число 1 ≤ m ≤ n.
Выход. Максимум подмассива A[i : : : i + m − 1] для всех 1 ≤
i ≤ n − m + 1.
-=-
Формат входа. Первая строка входа содержит число n, вторая — массив A[1 : : : n], третья — число m.
Формат выхода. n − m + 1 максимумов, разделённых пробелами.
Ограничения. 1 ≤ n ≤ 105, 1 ≤ m ≤ n, 0 ≤ A[i] ≤ 105 для всех 1 ≤ i ≤
n.
-=-

Пример.
Вход:
8
2 7 3 1 5 2 6 2
4
Выход:
7 7 5 6 6

Пример.
Вход:
3
2 1 5
1
Выход:
2 1 5

Пример.
Вход:
3
2 3 9
3
Выход:
9

Test input:
3
2 1 5
1

In [8]:
n = int(input())
s = input().split()
m = int(input())
stack = []
ma = []
flag = True
for i in range(n):
    s[i] = int(s[i])

for i in range(m):
    if i==0:
        maks= s[i]   
    elif maks<s[i]:
        maks = s[i]    
ma.append(maks) 

for i in range(m,n):
    print("ma",ma)
    print("s",s)
    if ma[i-m]<=s[i]:
        ma.append(s[i])
    else:
        ma.append(ma[i-m])
       
for i in range(n-m+1):
    print(ma[i])

3
2 1 5
1
ma [2]
s [2, 1, 5]
ma [2, 2]
s [2, 1, 5]
2
2
5


In [ ]:
from collections import deque

n = int(input())
s = input().split()
m = int(input())
stack = []
ma = []
flag = True
#buf=[-1 for i in range(n)]
#d = deque(m)
for i in range(n):
    s[i] = int(s[i])

for i in range(m):
    #d.append(s[i])
    if i==0:
        maks= i   
    elif s[maks]<s[i]:
        maks = i    
ma.append(maks) 
stack.append(maks) 

for i in range(m,n):
    #if j<n-m:   
    #d.popleft()
    #d.append(s[i]) 
    print("ma",ma)
    print("s",s)
    if s[ma[i-m]]<=s[i]:
        ma.append(i)
    else:
        ma.append(i-m)
       
for i in range(n-m+1):
    print(s[ma[i]])

In [9]:
from collections import deque
n = int(input())
s = input().split()
m = int(input())
stack = []
ma = []
flag = True
for i in range(n):
    s[i] = int(s[i])

for i in range(m):
    if i==0:
        maks= s[i]  
        j=i
        stack.append([i,s[i]])
    elif (maks<s[i]):
        maks = s[i] 
        j=i
        stack.append([i,s[i]])
ma.append(j,maks) 
j=0
d = deque(stack,m)
for i in range(m,n):
    print("ma",ma)
    print("s",s)
    #if j
    if ma[i-m]<=s[i]:# and j<m:
        stack.append([i,s[i]])
        ma.append([i,s[i]])
        #j=+1 #!!!WRONG must be j+=1
    else:
        ma.append([-1,ma[i-m]])
       
for i in range(n-m+1):
    print(ma[i])

3
2 1 5
1
ma [2]
s [2, 1, 5]
ma [2, 2]
s [2, 1, 5]
2
2
5


In [ ]:
http://e-maxx.ru/algo/stacks_for_minima



In [13]:
from collections import deque
n = int(input())
s = input().split()
m = int(input())
stack = []
ma = []
flag = True
for i in range(n):
    s[i] = int(s[i])

d = deque([s[i] for i in range(n) if i<=m],m)
#d = deque([],m)

for i in range(m):
    if i==0:
        maks = s[0]
        
        stack.append(s[i])
        d.append(s[0])
    elif (d[-1]<s[i]):
        d.popleft()
        maks = s[i] 
        stack.append(s[i])
        d.append(s[0])
    elif (d[-1]<s[i]):
        
ma.append(maks) 
j=0


for i in range(m,n):
    print("ma",ma)
    print("s",s)
    print(d)
    #if j
    p = d[0]
    if ma[i-m]<=s[i]:# and j<m:
        stack.append(s[i])
        ma.append(s[i])
        #j=+1 #!!!WRONG must be j+=1
    else:
        ma.append([ma[i-m]])
       
for i in range(n-m+1):
    print(ma[i])

2
1 2
1


IndexError: deque index out of range

In [ ]:
,7 3 2, 1
max=7
7, 3 2 1,
max=3 


In [27]:
Failed test #59 of 86. Time limit exceeded

from collections import deque
n = int(input())
s = input().split()
m = int(input())
stack = []
ma = []
flag = True
for i in range(n):
    s[i] = int(s[i])

d = deque([s[i] for i in range(n) if i<m],m)
#print("d",d)
maks=max(d)
ma.append(maks)

for i in range(m,n):
    #print(s[i])
    d.popleft()
    d.append(s[i])
    #print("d",d)
    maks=max(d)
    ma.append(maks)
        
    
#for i in range(n-m+1):
 #   print(ma[i])
    
for i in ma:
    print(i)
 
    

3
2 1 5
1
2
1
5


In [25]:
Test input:
3
2 1 5
1

SyntaxError: invalid syntax (<ipython-input-25-12604815f546>, line 1)

In [ ]:
Failed test #59 of 86. Time limit exceeded

from collections import deque
n = int(input())
s = input().split()
m = int(input())
#stack = []
ma = []
#flag = True
for i in range(n):
    s[i] = int(s[i])

d = deque([s[i] for i in range(n) if i<m],m)
#print("d",d)
ma.append(max(d))

for i in range(m,n):
    #print(s[i])
    d.popleft()
    d.append(s[i])
    #print("d",d)    
    ma.append(max(d))
        
    
#for i in range(n-m+1):
 #   print(ma[i])
    
for i in ma:
    print(i)
 
    

In [ ]:
#Failed test #59 of 86. Time limit exceeded
from collections import deque
n = int(input())
s = input().split()
m = int(input())

for i in range(n):
    s[i] = int(s[i])

d = deque([s[i] for i in range(n) if i<m],m)
print(max(d))

for i in range(m,n):
    d.popleft()
    d.append(s[i])  
    print(max(d))

In [ ]:
#Failed test #59 of 86. Time limit exceeded

from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []

for i in range(n):
    s[i] = int(s[i])

d = deque([s[i] for i in range(n) if i<m],m)

ma.append(max(d))

for i in range(m,n):
    if s[i]>=ma[-1] and d[0]!=s[i]:
        ma.append(s[i])
        d.popleft()
        d.append(s[i])   
    else:
        d.popleft()
        d.append(s[i])   
        ma.append(max(d))

for i in ma:
    print(i)

In [ ]:
#Failed test #59 of 86. Time limit exceeded

from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []

for i in range(n):
    s[i] = int(s[i])

#st = [s[i] for i in range(n) if i<m]

#ma.append(max(st))
#Failed test #59 of 86. Time limit exceeded

from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []
st = []

for i in range(n):
    s[i] = int(s[i])

#st = [s[i] for i in range(n) if i<m]

#ma.append(max(st))

ma.append(s[0])
for i in range(m,n):    
    if s[i-m]>ma[-1]:
        ma.append(s[i-m])
    elif s[i-m]<ma[-1] and m>1:
        ma.append(ma[-1])
    else:
        st = s[i-m:i]
        ma.append(max(st))

#     if s[i]>=ma[-1] and d[0]!=s[i]:
#         ma.append(s[i])
#         d.popleft()
#         d.append(s[i])   
#     else:
#         d.popleft()
#         d.append(s[i])   
#         ma.append(max(d))

for i in range(len(ma)-1):
    print(ma[i+1])
    
#     if s[i]>=ma[-1] and d[0]!=s[i]:
#         ma.append(s[i])
#         d.popleft()
#         d.append(s[i])   
#     else:
#         d.popleft()
#         d.append(s[i])   
#         ma.append(max(d))

# for i in ma:
#     print(i)



In [ ]:
Test input:
8
2 7 3 1 5 2 6 2
4

Correct output:
7 7 5 6 6

In [4]:



from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []
st = []

for i in range(n):
    s[i] = int(s[i])

#st = [s[i] for i in range(n) if i<m]
st1=[-1,]
#ma.append(max(st))

#stm = deque([[s[i],i] for i in range(n) if i<m],m)
#stl = deque([s[i] for i in range(n) if i<m],m)
stm= deque()
ma.append(s[0])
stm.append(s[0])

for i in range(m,n):    
    if s[i-m]>ma[-1]:        
        ma.append(s[i-m])
        stm.append([s[i],i])
    #elif s[i-m]<ma[-1] and m>1:
        #ma.append(ma[-1])
    else:
        st = s[i-m:i]
        ma.append(max(st))

#     if s[i]>=ma[-1] and d[0]!=s[i]:
#         ma.append(s[i])
#         d.popleft()
#         d.append(s[i])   
#     else:
#         d.popleft()
#         d.append(s[i])   
#         ma.append(max(d))

for i in range(len(ma)-1):
    print(ma[i+1])
    
#     if s[i]>=ma[-1] and d[0]!=s[i]:
#         ma.append(s[i])
#         d.popleft()
#         d.append(s[i])   
#     else:
#         d.popleft()
#         d.append(s[i])   
#         ma.append(max(d))

# for i in ma:
#     print(i)



3
1 2 3
1
1
1


In [2]:
from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []
st = []
d=deque([],m)

for i in range(n):
    s[i] = int(s[i])

#st = [s[i] for i in range(n) if i<m]

#ma.append(max(st))

ma.append(s[0])
for i in range(m,n+1):    
    #print(s[i-m],ma[-1])
    if s[i-m]>ma[-1]:
        ma.append(s[i-m])
        #print(ma)
    #elif s[i-m]<ma[-1] and ma[-1]:
        #ma.append(ma[-1])
    else:
        st = s[i-m:i]
        ma.append(max(st))

for i in range(len(ma)-1):
    print(ma[i+1])

3
1 2 3
1
1
2
3


In [44]:
#Failed test #62 of 86. Time limit exceeded

from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []
st = []


for i in range(n):
    s[i] = int(s[i])
    
dl=deque([],m)
dr=deque([],m)
#st = [s[i] for i in range(n) if i<m]

#ma.append(max(st))
for i in range(m):
    print(s[i], dl)
    if i==0 or s[i]>=dl[-1][0]:
        dl.append([s[i],i])
    else:
        j=0
        while dl and dl[0][0]<s[i] and j<m:
            print("j",j)
            dr.append(dl[0])
            print("dr",dr)
            dl.popleft()
            print("dl",dl)
            j=+1    #!!!WRONG must be j+=1        
        print("d_l",dl)
        print("d_r",dr)        
        dl.appendleft([s[i],i])
        dl.extendleft(reversed(dr))
        dr.clear()
    print("dl=",dl) 
print("dl_",dl)        
#dl=deque([s[0],],m)
ma.append(dl[-1][0])
for i in range(m,n):    
    print("__", i-m)
    for j in dl:
        if j[1]<=(i-m):
            print(j)
            dl.remove(j)
            break   
    #print(s[i-m],ma[-1])
    print(s[i],dl)    
    if s[i]>=ma[-1]:
        #dl.popleft()
        dl.append([s[i],i])
        ma.append(s[i])    
        #print(ma)
    #lif s[i-m]<ma[-1] and ma[-1]:
        #ma.append(ma[-1])
    else:     
        j=0
        while dl and dl[0][0]<s[i] and j<m:
            dr.append(dl[0])
            dl.popleft()
            j=+1           #!!!!WRONG must be j+=1 
        dl.appendleft([s[i],i])
        dl.extendleft(reversed(dr))
        dr.clear()
        #st = s[i-m:i]        
        ma.append(dl[-1][0])

        
for i in ma:
    print(i)

3
1 2 3
1
1 deque([], maxlen=1)
dl= deque([[1, 0]], maxlen=1)
dl_ deque([[1, 0]], maxlen=1)
__ 0
[1, 0]
2 deque([], maxlen=1)
__ 1
[2, 1]
3 deque([], maxlen=1)
1
2
3


In [6]:
L = [0,10,20,40]
L[::-1]

[40, 20, 10, 0]

In [ ]:


This is a sample test from the problem statement!

Test input:
8
2 7 3 1 5 2 6 2
4

Correct output:
7 7 5 6 6

Your code output:
2
7
3
1
5

In [9]:
dl=deque([1,2,],4)
dl.append(3)
dl.extendleft([0,6,7,])
dl

deque([7, 6, 0, 1])

In [ ]:
https://stepik.org/lesson/41234/step/5?discussion=611366&unit=19818
https://habr.com/ru/post/116236/


In [57]:

#from collections import deque
n = int(input())
s = input().split()
m = int(input())
ma = []

for i in range(n):
    s[i] = int(s[i])

b = [[0,s[0]]]
c = [[0,s[m-1]]]
#for z in range(n//(m-1)):      
       
print("j", j, "z", z)
for i in range(0,n):      
    j=i//m
    z=i%m 
    #b[j,[z]]=max()    
        
    if z==(m-1):
        b.append([j+1,s[i]])        
        
    elif s[i]>=b[-1][1]:
        b.append([j,s[i]])
    else:
        print(s[i])
        print("b[-2][1]]",b[-2][1])
        b.append([j,b[-2][1]])
    #if s[i]>=b[i]
        #b.append(s[i])
    #else:
        #b.append(b[-1])
    
    
for i in b:
    print(i)
for i in ma:
    print(i)

9
2 7 3 1 5 2 6 2 1
4
j 2 z 0
3
b[-2][1]] 2
2
b[-2][1]] 1
1
b[-2][1]] 6
[0, 2]
[0, 2]
[0, 7]
[0, 2]
[1, 1]
[1, 5]
[1, 1]
[1, 6]
[2, 2]
[2, 6]


In [45]:
5//2

2

In [ ]:
2 7 3 1 5 2 6 2 1

In [28]:
import numpy as np
import math
ma=[]
b=[]
c=[]
#a=np.array([2,7,3,1,5,2,6,2,1], ndmin=3)
m=4
n=10
li=[2,7,3,1,5,2,6,2,1,0]
m1=math.ceil(n/(m-1))
m2=math.ceil(n/m)
e=[-1 for i in range(m1*(m-1)-n)]
li.extend(e)
a=np.array(li)

a=np.reshape(a,(m1, m-1))
ma=np.array([-1 for i in range(m2)])
b=np.array([[-1 for j in range(m-1)] for i in range(m1)])
c=np.array([[-1 for j in range(m-1)] for i in range(m1)])
print("b",b)
print("c",c)
print("m1",m1)
print("m2",m2)
for i in range(m1):
    for j in range(m-1):
        print(a[i][j])

for i in range(m1):
    for j in range(m-1):
        if a[i][j]>b[i][j]:
           b[i][j] = a[i][j] 
        print(a[i][m-2-j])
        if a[i][m-2-j]>c[i][m-2-j]:
           c[i][m-2-j] = a[i][j] 
print("b",b)
print("c",c)
b=b.flat
c=c.flat
for i in range(m2):            
    ma[i]=b[i*m] if b[i*m]>c[i*m] else c[i*m]
    print(ma[i])

b [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
c [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
m1 4
m2 3
2
7
3
1
5
2
6
2
1
0
-1
-1
3
7
2
2
5
1
1
2
6
-1
-1
0
b [[ 2  7  3]
 [ 1  5  2]
 [ 6  2  1]
 [ 0 -1 -1]]
c [[ 3  7  2]
 [ 2  5  1]
 [ 1  2  6]
 [-1 -1 -1]]
3
5
6


In [9]:
import numpy as np
v=np.indices((3,3))
v=v.flat
v[7]

2

In [40]:
import numpy as np
import math
ma=[]
b=[]
c=[]
n = int(input())
li = list(map(int,input().split()))
m = int(input())
#a=np.array([2,7,3,1,5,2,6,2,1], ndmin=3)
#m=4
#n=10
#li=[2,7,3,1,5,2,6,2,1,0]
m1=math.ceil(n/(m-1))
m2=math.ceil(n/m)
e=[-1 for i in range(m1*(m-1)-n)]
li.extend(e)
a=np.array(li)

a=np.reshape(a,(m1, m-1))
ma=np.array([-1 for i in range(n-m)])
b=np.array([[-1 for j in range(m-1)] for i in range(m1)])
c=np.array([[-1 for j in range(m-1)] for i in range(m1)])
print("b",b)
print("c",c)
print("m1",m1)
print("m2",m2)
for i in range(m1):
    for j in range(m-1):
        print(a[i][j])

for i in range(m1):
    for j in range(m-1):
        if a[i][j]>b[i][j]:
           b[i][j] = a[i][j] 
        print(a[i][m-2-j])
        if a[i][m-2-j]>c[i][m-2-j]:
           c[i][m-2-j] = a[i][j] 
print("b",b)
print("c",c)
b=b.flat
c=c.flat
print("b",b)
print("c",c)
for i in range(m,n):            
    #ma[i]=b[i*m] if b[i*m]>c[i*m] else c[i*m]
    print("i,b[i],c[i-m]",i,b[i],c[i-m])
    ma[i-m]=b[i] if b[i]>c[i-m] else c[i-m]
    print(ma[i-m])

8
2 7 3 1 5 2 6 2
4
b [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
c [[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]
m1 3
m2 2
2
7
3
1
5
2
6
2
-1
3
7
2
2
5
1
-1
2
6
b [[ 2  7  3]
 [ 1  5  2]
 [ 6  2 -1]]
c [[ 3  7  2]
 [ 2  5  1]
 [-1  2 -1]]
b <numpy.flatiter object at 0x000001EFFAF20370>
c <numpy.flatiter object at 0x000001EFFAF20DC0>
i,b[i],c[i-m] 4 5 3
5
i,b[i],c[i-m] 5 2 7
7
i,b[i],c[i-m] 6 6 2
6
i,b[i],c[i-m] 7 2 2
2


In [ ]:
Test input:
8
2 7 3 1 5 2 6 2
4

Correct output:
7 7 5 6 6

In [22]:
import numpy as np
import math
ma=[]
b=[]
c=[]
n = int(input())
li = list(map(int,input().split()))
m = int(input())
#a=np.array([2,7,3,1,5,2,6,2,1], ndmin=3)
#m=4
#n=10
#li=[2,7,3,1,5,2,6,2,1,0]
if m==1:
    for i in li:
        print(i)
else:
    #m1=math.ceil(n/(m-1)) if m!=1 else n
    m1=math.ceil(n/(m-1)) if m!=1 else n
    m2=math.ceil(n/m)  
    e=[-1 for i in range(m1*(m-1)-n)]
    li.extend(e)
    a=np.array(li)

    #a=np.reshape(a,(m1, m-1)) if m!=1 else np.reshape(a,(m1, m))
    a=np.reshape(a,(m1, m-1))

    ma=np.array([-1 for i in range(n-m+1)])
    b=np.array([[-1 for j in range(m-1)] for i in range(m1)])
    c=np.array([[-1 for j in range(m-1)] for i in range(m1)])
    print("b",b)
    print("c",c)
    print("m1",m1)
    print("m2",m2)


    for i in range(m1):
        #b[i][0]=a[i][0]
        #c[i][m-1]=a[i][m-1]
        lastb=a[i][0]
        lastc=a[i][m-2]
        for j in range(m-1):
            if a[i][j]>lastb:
                b[i][j] = a[i][j]
                lastb=a[i][j]        
            else:
                b[i][j] = lastb 
            print(a[i][-j])
            print("lastc",lastc)
            if a[i][-1-j]>lastc:
                c[i][m-2-j] = a[i][-1-j]
                lastc = a[i][-1-j]
            else:            
                c[i][m-2-j] = lastc 
            print("c[i][m-2-j]",c[i][m-2-j])
    print("b",b)
    print("c",c)
    b=b.flat
    c=c.flat
    print("b",end=': ')
    [print(i,end=' ') for i in b]
    print("\n")
    #print("b",i)
    print("\nc",end=': ')
    [print(i,end=' ') for i in c]
    print("\n")
    for i in range(m,n+1):            
        #ma[i]=b[i*m] if b[i*m]>c[i*m] else c[i*m]
        print("i,b[i],c[i-m]",i,b[i-1],c[i-m])
        ma[i-m]=b[i-1] if b[i-1]>c[i-m] else c[i-m]
        print(ma[i-m])

3
2 3 9
3
b [[-1 -1]
 [-1 -1]]
c [[-1 -1]
 [-1 -1]]
m1 2
m2 1
2
lastc 3
c[i][m-2-j] 3
3
lastc 3
c[i][m-2-j] 3
9
lastc -1
c[i][m-2-j] -1
-1
lastc -1
c[i][m-2-j] 9
b [[2 3]
 [9 9]]
c [[ 3  3]
 [ 9 -1]]
b: 2 3 9 9 


c: 3 3 9 -1 

i,b[i],c[i-m] 3 9 3
9


In [ ]:
Test input:
8
2 7 3 1 5 2 6 2
4

Correct output:
7 7 5 6 6

Пример. Вход: 8 2 7 3 1 5 2 6 2 4 Выход: 7 7 5 6 6

Пример. Вход: 3 2 1 5 1 Выход: 2 1 5

Пример. Вход: 3 2 3 9 3 Выход: 9

In [18]:
m=1
n=3
li=[1,2,3]
m1=math.ceil(n/(m-1)) if m!=1 else n
m2=math.ceil(n/m)  
e=[-1 for i in range(m1*(m-1)-n)]
li.extend(e)
a=np.array(li)

a=np.reshape(a,(m1, m-1)) if m!=1 else np.reshape(a,(m1, m))
a

array([[1],
       [2],
       [3]])

In [ ]:
##! WOOORKSS!
import numpy as np
import math
ma=[]
b=[]
c=[]
n = int(input())
li = list(map(int,input().split()))
m = int(input())
#a=np.array([2,7,3,1,5,2,6,2,1], ndmin=3)
#m=4
#n=10
#li=[2,7,3,1,5,2,6,2,1,0]
if m==1:
    for i in li:
        print(i)
else:
    #m1=math.ceil(n/(m-1)) if m!=1 else n
    m1=math.ceil(n/(m-1)) if m!=1 else n
    m2=math.ceil(n/m)  
    e=[-1 for i in range(m1*(m-1)-n)]
    li.extend(e)
    a=np.array(li)

    #a=np.reshape(a,(m1, m-1)) if m!=1 else np.reshape(a,(m1, m))
    a=np.reshape(a,(m1, m-1))

    ma=np.array([-1 for i in range(n-m+1)])
    b=np.array([[-1 for j in range(m-1)] for i in range(m1)])
    c=np.array([[-1 for j in range(m-1)] for i in range(m1)])
#     print("b",b)
#     print("c",c)
#     print("m1",m1)
#     print("m2",m2)


    for i in range(m1):
        #b[i][0]=a[i][0]
        #c[i][m-1]=a[i][m-1]
        lastb=a[i][0]
        lastc=a[i][m-2]
        for j in range(m-1):
            if a[i][j]>lastb:
                b[i][j] = a[i][j]
                lastb=a[i][j]        
            else:
                b[i][j] = lastb 
#             print(a[i][-j])
#             print("lastc",lastc)
            if a[i][-1-j]>lastc:
                c[i][m-2-j] = a[i][-1-j]
                lastc = a[i][-1-j]
            else:            
                c[i][m-2-j] = lastc 
#             print("c[i][m-2-j]",c[i][m-2-j])
#     print("b",b)
#     print("c",c)
    b=b.flat
    c=c.flat
#     print("b",end=': ')
#     [print(i,end=' ') for i in b]
#     print("\n")
    #print("b",i)
#     print("\nc",end=': ')
#     [print(i,end=' ') for i in c]
#     print("\n")
    for i in range(m,n+1):            
        #ma[i]=b[i*m] if b[i*m]>c[i*m] else c[i*m]
#         print("i,b[i],c[i-m]",i,b[i-1],c[i-m])
        ma[i-m]=b[i-1] if b[i-1]>c[i-m] else c[i-m]
        print(ma[i-m])