In [2]:
#2.2.5
import math
y = [[0 for i in range(2)] for i in range(4)]
y[0] = [0.99,0.01]
y[1] = [0.5,0.5]
y[2] = [0.99,0.45]
y[3] = [0.65,0.65]
for i in y:
    print(-math.log(i[0])-math.log(i[1])) 

4.615220521841592
1.3862943611198906
0.8085580320712731
0.8615658321849085


In [9]:
#2.3.2
import sympy.parsing.sympy_parser

# from sympy import *
# x, y, z, t = symbols('x y z t')
x, y, w, b = symbols('x y w b')
# k, m, n = symbols('k m n', integer=True)
# f, g, h = symbols('f g h', cls=Function)

# f = diff(cos(x), x)
t =1/(1+exp(-w*x-b))
sample_expr_str = f'diff(-y*log({t})-(1-y)*log(1-({t})), w)'
sample_expr = sympy.parsing.sympy_parser.parse_expr(sample_expr_str)
sample_value = sample_expr.evalf(subs=dict(x=0.5, y=1, w=4, b=1))
print(sample_value)

-0.0237129365887834


In [ ]:
#right answer
diff(-y*log(1/(1+exp(-w*x-b)))-(1-y)*log(1-(1/(1+exp(-w*x-b)))), w)
diff(-y*log(1/(1+exp(-w*x-b)))-(1-y)*log(1-(1/(1+exp(-w*x-b)))), b).simplify()

In [ ]:
#2.3.5
w - t*diff(-y*log(1/(1+exp(-w*x-b)))-(1-y)*log(1-(1/(1+exp(-w*x-b))))+c*(w**2+b**2), w).simplify()

In [11]:
#2.3.7
import sys
import numpy as np


def parse_array(s):
    return np.array([int(s.strip()) for s in s.strip().split(' ')])

def read_array():
    return parse_array(sys.stdin.readline())

def calculate_pmi(a, b):
    p_a = sum(a)/len(a)
    p_b = sum(b)/len(b)
    #p = len (set(a)&set(b))  #intersection
    c = [1 if a[i]==1 and b[i]==1 else 0 for i in range(len(a)) ]
    p_c = sum(c)/len(c)
    res = np.log(p_c/p_a/p_b)
    return res  # ваше решение

a = read_array()
b = read_array()
pmi_value = calculate_pmi(a, b)

print('{:.6f}'.format(pmi_value))

ValueError: invalid literal for int() with base 10: ''

In [14]:
su = 0
for i in range(1,11):
    su+=i**(-2)
#su
r = 1/(su*100)
r

0.006452579827864143

In [16]:
su = 0
r = 0
ro = 0
for j in range(1,12):
    for i in range(1,j):
        su+=i**(-2)
    r = 1/(su*100)
    ro +=r
ro

ZeroDivisionError: division by zero

In [6]:
# https://stepik.org/lesson/261086/step/8?discussion=1427903&unit=241830
# считаем сначала Z. Можно так: sum([1/x**2 for x in range(1,1000)])
# далее решаем уравнение 
# 1/(Z*k**s) < 0.001 (10/10000)
# или Z*k**2 <1000
# находим k (округляем в меньшую сторону) и вычитаем из 1000 k
su = 0
r = 0
ro = 0
for i in range(1,1000):
    su+=i**(-2)
print(su) #1.6439335666815615
d = 1/(100*su)
k = (1000/su)**0.5
k

1.6439335666815615


24.663679512615907

In [16]:
#2.4.3
import re
import sys


# модифицируйте это регулярное выражение
#TOKENIZE_RE = re.compile(r'[\w\d]+', re.I)
TOKENIZE_RE = re.compile(r'[а-яё]+|-?\d*[.,]?\d+|[d*]|\S', re.I)#[:punct:]|

def tokenize(txt):
    return TOKENIZE_RE.findall(txt)


#for line in sys.stdin:
s = input()
print(' '.join(tokenize(s.strip().lower())))



Какого ;%:?* тут происходит?
какого ; % : ? * тут происходит ?


In [14]:
N = sys.stdin.readline()
print(N)

In [ ]:
Контактный телефон: 123123. 	контактный телефон : 123123 .
Что-нибудь надо придумать. 	что - нибудь надо придумать .
Значение числа Е=2.7182. 	значение числа е = 2.7182 .
Демон123, как тебя зовут в реале? 	демон 123 , как тебя зовут в реале ?
-1-.15=-1.15 	-1 -.15 = -1.15
- 1 - .15 = -1.15 	- 1 - .15 = -1.15
Какого ;%:?* тут происходит? 	какого ; % : ? * тут происходит ?

In [21]:
#2.4.5
import collections, re

s=["Казнить нельзя, помиловать. Нельзя наказывать.",
    "Казнить, нельзя помиловать. Нельзя освободить.",
    "Нельзя не помиловать.",
    "Обязательно освободить.",]
size = 0
TOKENIZE_RE = re.compile(r'[\w\d]+', re.I)
def tokenize(txt):
    return TOKENIZE_RE.findall(txt.lower()) 

d = collections.defaultdict(int)
#print (d)
for line in s:
    t = tokenize(line)
    size+=1
    unique = set(t)
    for token in unique:
        d[token]+=1
ds = {k:(v/size) for k,v  in d.items() }
ds = sorted(ds.items(), key = lambda pair:(pair[1],pair[0]))
#print (ds)
[print(k[0], end = " ") for k in ds]
print ()
[print(k[1], end = " ") for k in ds]

наказывать не обязательно казнить освободить нельзя помиловать 
0.25 0.25 0.25 0.5 0.5 0.75 0.75 

[None, None, None, None, None, None, None]

In [28]:
#https://stepik.org/lesson/256724/step/5?discussion=1545582&unit=237035
corpus = [
    'Казнить нельзя, помиловать. Нельзя наказывать.',
    'Казнить, нельзя помиловать. Нельзя освободить.',
    'Нельзя не помиловать.',
    'Обязательно освободить.']

## Получение df
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(smooth_idf=False, use_idf=True)
vectorizer.fit_transform(corpus)
word_doc_freq = 1/np.exp(vectorizer.idf_ - 1) ## ВОТ ОСОБЕННОСТЬ ПЕРЕВОДА ИЗ IDF В DF
#Словарь тут: 
vectorizer.get_feature_names()
vectorizer.idf_
b = zip(vectorizer.get_feature_names(),vectorizer.idf_)
list(b)


[('казнить', 1.6931471805599454),
 ('наказывать', 2.386294361119891),
 ('не', 2.386294361119891),
 ('нельзя', 1.2876820724517808),
 ('обязательно', 2.386294361119891),
 ('освободить', 1.6931471805599454),
 ('помиловать', 1.2876820724517808)]

In [36]:
#2.4.5
import collections, re, numpy as np

s=["Казнить нельзя, помиловать. Нельзя наказывать.",
    "Казнить, нельзя помиловать. Нельзя освободить.",
    "Нельзя не помиловать.",
    "Обязательно освободить.",]
size = 0
TOKENIZE_RE = re.compile(r'[\w\d]+', re.I)
def tokenize(txt):
    return TOKENIZE_RE.findall(txt.lower()) 

d = collections.defaultdict(int)
#print (d)
for line in s:
    t = tokenize(line)
    size+=1
    unique = set(t)
    for token in unique:
        d[token]+=1
ds = {k:(v/size) for k,v  in d.items() }
ds = sorted(ds.items(), key = lambda pair:(pair[1],pair[0]))
print (ds)
print(list(enumerate(ds)))
w = {word: i for i, (word, _) in enumerate(ds)}
print (w)
w2 = np.array([cnt for _, cnt in ds], dtype='float32')
print (w2)
[print(k, end = " ") for k in w]
print ()
[print(k, end = " ") for k in w2]

[('наказывать', 0.25), ('не', 0.25), ('обязательно', 0.25), ('казнить', 0.5), ('освободить', 0.5), ('нельзя', 0.75), ('помиловать', 0.75)]
[(0, ('наказывать', 0.25)), (1, ('не', 0.25)), (2, ('обязательно', 0.25)), (3, ('казнить', 0.5)), (4, ('освободить', 0.5)), (5, ('нельзя', 0.75)), (6, ('помиловать', 0.75))]
{'наказывать': 0, 'не': 1, 'обязательно': 2, 'казнить': 3, 'освободить': 4, 'нельзя': 5, 'помиловать': 6}
[0.25 0.25 0.25 0.5  0.5  0.75 0.75]
наказывать не обязательно казнить освободить нельзя помиловать 
0.25 0.25 0.25 0.5 0.5 0.75 0.75 

[None, None, None, None, None, None, None]

In [50]:
#2.4.5
import collections, re, numpy as np

s=["Казнить нельзя, помиловать. Нельзя наказывать.",
    "Казнить, нельзя помиловать. Нельзя освободить.",
    "Нельзя не помиловать.",
    "Обязательно освободить.",]
size = 0
TOKENIZE_RE = re.compile(r'[\w\d]+', re.I)
def tokenize(txt):
    return TOKENIZE_RE.findall(txt.lower()) 

d = collections.defaultdict(int)
#print (d)
for line in s:
    t = tokenize(line)
    size+=1
    unique = set(t)
    for token in unique:
        d[token]+=1
ds = {k:(v/size) for k,v  in d.items() }
ds = sorted(ds.items(), key = lambda pair:(pair[1],pair[0]))
#print (ds)
#print(list(enumerate(ds)))
w = {word: i for i, (word, _) in enumerate(ds)}
#print (w)
w2 = np.array([cnt for _, cnt in ds], dtype='float32')
#print (w2)
[print(f'{k}:{v}', end = " ") for k,v in w.items()]
print ()
[print(f'{k}', end = " ") for k,v in w.items()]
print ()
[print(k, end = " ") for k in w2]

наказывать:0 не:1 обязательно:2 казнить:3 освободить:4 нельзя:5 помиловать:6 0 1 2 3 4 5 6 
0.25 0.25 0.25 0.5 0.5 0.75 0.75 

[None, None, None, None, None, None, None]

In [49]:
#https://github.com/Samsung-IT-Academy/stepik-dl-nlp/blob/master/dlnlputils/data/base.py#L34
import collections
import re

import numpy as np

TOKEN_RE = re.compile(r'[\w\d]+')

texts = ["Казнить нельзя, помиловать. Нельзя наказывать.",
    "Казнить, нельзя помиловать. Нельзя освободить.",
    "Нельзя не помиловать.",
    "Обязательно освободить.",]

def tokenize_text_simple_regex(txt, min_token_size=1):
    txt = txt.lower()
    all_tokens = TOKEN_RE.findall(txt)
    return [token for token in all_tokens if len(token) >= min_token_size]


def character_tokenize(txt):
    return list(txt)


def tokenize_corpus(texts, tokenizer=tokenize_text_simple_regex, **tokenizer_kwargs):
    return [tokenizer(text, **tokenizer_kwargs) for text in texts]


def add_fake_token(word2id, token='<PAD>'):
    word2id_new = {token: i + 1 for token, i in word2id.items()}
    word2id_new[token] = 0
    return word2id_new


def texts_to_token_ids(tokenized_texts, word2id):
    return [[word2id[token] for token in text if token in word2id]
            for text in tokenized_texts]


def build_vocabulary(tokenized_texts, max_size=1000000, max_doc_freq=1, min_count=1, pad_word=None):
    word_counts = collections.defaultdict(int)
    doc_n = 0

    # посчитать количество документов, в которых употребляется каждое слово
    # а также общее количество документов
    for txt in tokenized_texts:
        doc_n += 1
        unique_text_tokens = set(txt)
        for token in unique_text_tokens:
            word_counts[token] += 1

    # убрать слишком редкие и слишком частые слова
    word_counts = {word: cnt for word, cnt in word_counts.items()
                   if cnt >= min_count and cnt / doc_n <= max_doc_freq}

    # отсортировать слова по убыванию частоты
    sorted_word_counts = sorted(word_counts.items(),
                                #reverse=True,
                                key=lambda pair: pair[1])

    # добавим несуществующее слово с индексом 0 для удобства пакетной обработки
    if pad_word is not None:
        sorted_word_counts = [(pad_word, 0)] + sorted_word_counts

    # если у нас по прежнему слишком много слов, оставить только max_size самых частотных
    if len(word_counts) > max_size:
        sorted_word_counts = sorted_word_counts[:max_size]

    # нумеруем слова
    word2id = {word: i for i, (word, _) in enumerate(sorted_word_counts)}

    # нормируем частоты слов
    word2freq = np.array([cnt / doc_n for _, cnt in sorted_word_counts], dtype='float32')

    return word2id, word2freq


PAD_TOKEN = '__PAD__'
NUMERIC_TOKEN = '__NUMBER__'
NUMERIC_RE = re.compile(r'^([0-9.,e+\-]+|[mcxvi]+)$', re.I)


def replace_number_nokens(tokenized_texts):
    return [[token if not NUMERIC_RE.match(token) else NUMERIC_TOKEN for token in text]
            for text in tokenized_texts]

build_vocabulary(tokenize_corpus(texts))

({'наказывать': 0,
  'не': 1,
  'обязательно': 2,
  'казнить': 3,
  'освободить': 4,
  'помиловать': 5,
  'нельзя': 6},
 array([0.25, 0.25, 0.25, 0.5 , 0.5 , 0.75, 0.75], dtype=float32))

In [2]:
import collections, re, numpy as np

s=["Казнить нельзя, помиловать. Нельзя наказывать.",
    "Казнить, нельзя помиловать. Нельзя освободить.",
    "Нельзя не помиловать.",
    "Обязательно освободить.",]
size = 0
TOKENIZE_RE = re.compile(r'[\w\d]+', re.I)
def tokenize(txt):
    return TOKENIZE_RE.findall(txt.lower()) 

d = collections.defaultdict(int)
#print (d)
for line in s:
    t = tokenize(line)
    size+=1
    unique = set(t)
    for token in unique:
        d[token]+=1
ds = {k:(v/size) for k,v  in d.items() }
d1 = [(k,(v/size)) for k,v  in d.items() ]
##ds = sorted(ds.items(), key = lambda pair:(pair[1],pair[0]))
#print (ds)
#print(list(enumerate(ds)))
##w = {word: i for i, (word, _) in enumerate(ds)}
#print (w)
##w2 = np.array([cnt for _, cnt in ds], dtype='float32')
#print (w2)
# [print(f'{k}', end = " ") for k,v in w.items()]
# print ()
# [print(k, end = " ") for k in w2]
#https://stepik.org/lesson/256724/step/5?discussion=1265959&unit=237035
answer = sorted(d1, key=lambda x:(x[1],x[0]))
#print(answer)
answer_1 = [] 
answer_2 = []

for k, v in list(answer):
    answer_1.append(k)
    answer_2.append(str(v))
    
print(" ".join(answer_1))
print(" ".join(answer_2))

наказывать не обязательно казнить освободить нельзя помиловать
0.25 0.25 0.25 0.5 0.5 0.75 0.75


In [30]:
#2.4.7
import collections, re, math, numpy as np
import scipy.sparse

s=["Казнить нельзя, помиловать. Нельзя наказывать.",
    "Казнить, нельзя помиловать. Нельзя освободить.",
    "Нельзя не помиловать.",
    "Обязательно освободить.",]
size = 0
TOKENIZE_RE = re.compile(r'[\w\d]+', re.I)
def tokenize(txt):
    return TOKENIZE_RE.findall(txt.lower()) 

d = collections.defaultdict(int)
dd = collections.defaultdict(list)

te = []
for line in s:
    t = tokenize(line)
    te.append(t)
    size+=1
    unique = set(t)
    for token in unique:
        d[token]+=1
        dd[token].append(t.count(token))
print(te)
print ("d")
print (d)
print ("dd")
print (dd)
tf = {k:(v/size) for k,v  in d.items() }
tf = sorted(tf.items(), key = lambda pair:(pair[1],pair[0]))
print ("tf")
print (tf)
ltf = np.array([math.log1p(i[1]) for i in tf])
print(ltf)
res = []
num_docs = size
num_feats = len(d)
feature_matrix = np.zeros((num_docs, num_feats))
result = scipy.sparse.dok_matrix((num_docs, num_feats), dtype='float32')
w = {word: i for i, (word, _) in enumerate(tf)}
print("w")
print(w)
print("feature_matrix")
for i in range(num_docs):    
    for j  in te[i]:        
        if j in w:
#             print("j,w[j]")
#             print(j,w[j])
            feature_matrix[i][w[j]] += 1
            result[i,w[j]] += 1
#         print("feature_matrix[i]")
#         print(feature_matrix[i])
print(feature_matrix)
print("result7")
print(result)
print("8")
print(result.sum(1))

#f4 = f2(feature_matrix.sum(0))
#f6=f5(result.sum(1))
#print(f6)
#print(np.vectorize(math.log1p(i for i in result.sum(1))))

#fm = feature_matrix*f5
print("fm")
print(np.sum(feature_matrix, axis = 1))
print("9")
#print([math.log1p(result.sum(1))])
result = result.multiply(1 / result.sum(1))
feature_matrix = feature_matrix/np.sum(feature_matrix, axis = 1).reshape(4,1)
print(feature_matrix)
def f_1(x):
    return math.log1p(x)
f2 = np.vectorize(f_1)
feature_matrix = f2(feature_matrix)
print(feature_matrix)
#result = result.multiply(1 / f3)  # разделить каждую строку на её длину   TF
result1 = result.multiply(1 / result.sum(1))  # разделить каждую строку на её длину   TF
result = f2(result.toarray()) ### doesnt work:TypeError: must be real number, not coo_matrix
#result = coo_matrix(result, shape=(4, 4))
result = scipy.sparse.dok_matrix(result,(num_docs, num_feats), dtype='float32')
print("result")
print(result)
#word2freq = 1
word2freq = np.array([g[1] for g in tf])
print(word2freq)
idf = [size/len(v) for v in dd.values()]
print("idf")
print(idf)
feature_matrix = feature_matrix*idf
result = result.multiply(idf)
#word2freq = np.array([cnt / doc_n for _, cnt in sorted_word_counts], dtype='float32')
#result = result.multiply(1 / word2freq)#np.vectorize(word2freq))  # разделить каждый столбец на вес слова
print("result")
print(result)
#result1 = result1.multiply(1 / word2freq)#np.vectorize(word2freq))  # разделить каждый столбец на вес слова
print("feature_matrix")
print(feature_matrix)

mean1 = feature_matrix.mean(0)
print(mean1)
mean = result.mean(0)
print(mean)
feature_matrix = feature_matrix - mean1
print(feature_matrix)
mean1 = feature_matrix.mean(0)
print(mean1)
mean = result.mean(0)
print(mean)
result = result - mean
print(result)

feats_std1 = feature_matrix.std(0, ddof=1)
print(feats_std1)
feature_matrix = feature_matrix/feats_std1
print(feature_matrix)
#feats_std = result.toarray().std(0, ddof=1) ###??? wtf: AttributeError: 'matrix' object has no attribute 'toarray'
#print(feats_std)
#[0.1215477  0.57536414 0.27031007 0.2105268  0.38517496 0.64699208 0.47811428]


[['казнить', 'нельзя', 'помиловать', 'нельзя', 'наказывать'], ['казнить', 'нельзя', 'помиловать', 'нельзя', 'освободить'], ['нельзя', 'не', 'помиловать'], ['обязательно', 'освободить']]
d
defaultdict(<class 'int'>, {'нельзя': 3, 'наказывать': 1, 'помиловать': 3, 'казнить': 2, 'освободить': 2, 'не': 1, 'обязательно': 1})
dd
defaultdict(<class 'list'>, {'нельзя': [2, 2, 1], 'наказывать': [1], 'помиловать': [1, 1, 1], 'казнить': [1, 1], 'освободить': [1, 1], 'не': [1], 'обязательно': [1]})
tf
[('наказывать', 0.25), ('не', 0.25), ('обязательно', 0.25), ('казнить', 0.5), ('освободить', 0.5), ('нельзя', 0.75), ('помиловать', 0.75)]
[0.22314355 0.22314355 0.22314355 0.40546511 0.40546511 0.55961579
 0.55961579]
w
{'наказывать': 0, 'не': 1, 'обязательно': 2, 'казнить': 3, 'освободить': 4, 'нельзя': 5, 'помиловать': 6}
feature_matrix
[[1. 0. 0. 1. 0. 2. 1.]
 [0. 0. 0. 1. 1. 2. 1.]
 [0. 1. 0. 0. 0. 1. 1.]
 [0. 0. 1. 0. 1. 0. 0.]]
result7
  (0, 3)	1.0
  (0, 5)	2.0
  (0, 6)	1.0
  (0, 0)	1.0
  (1, 

In [6]:
#1.5  -0.5 -0.5 0.87 -0.76 0.6 0.16
#0.5 -0.5 -0.5 0.87 0.18  0.595 0.1609

def f_1(x):
    return np.int(x)

for t in range(5):
    f2 = np.vectorize(f_1)

    x = np.arange(1, 5, 0.9)
    print(x, f2(x))

[1.  1.9 2.8 3.7 4.6] [1 1 2 3 4]
[1.  1.9 2.8 3.7 4.6] [1 1 2 3 4]
[1.  1.9 2.8 3.7 4.6] [1 1 2 3 4]
[1.  1.9 2.8 3.7 4.6] [1 1 2 3 4]
[1.  1.9 2.8 3.7 4.6] [1 1 2 3 4]


In [ ]:
#https://github.com/Samsung-IT-Academy/stepik-dl-nlp/blob/master/dlnlputils/data/bag_of_words.py
import numpy as np
import scipy.sparse
import torch
from torch.utils.data import Dataset


def vectorize_texts(tokenized_texts, word2id, word2freq, mode='tfidf', scale=True):
    assert mode in {'tfidf', 'idf', 'tf', 'bin'}

    # считаем количество употреблений каждого слова в каждом документе
    result = scipy.sparse.dok_matrix((len(tokenized_texts), len(word2id)), dtype='float32')
    for text_i, text in enumerate(tokenized_texts):
        for token in text:
            if token in word2id:
                result[text_i, word2id[token]] += 1

    # получаем бинарные вектора "встречается или нет"
    if mode == 'bin':
        result = (result > 0).astype('float32')

    # получаем вектора относительных частот слова в документе
    elif mode == 'tf':
        result = result.tocsr()
        result = result.multiply(1 / result.sum(1))

    # полностью убираем информацию о количестве употреблений слова в данном документе,
    # но оставляем информацию о частотности слова в корпусе в целом
    elif mode == 'idf':
        result = (result > 0).astype('float32').multiply(1 / word2freq)

    # учитываем всю информацию, которая у нас есть:
    # частоту слова в документе и частоту слова в корпусе
    elif mode == 'tfidf':
        result = result.tocsr()
        result = result.multiply(1 / result.sum(1))  # разделить каждую строку на её длину
        result = result.multiply(1 / word2freq)  # разделить каждый столбец на вес слова

    if scale:
        result = result.tocsc()
        result -= result.min()
        result /= (result.max() + 1e-6)

    return result.tocsr()


class SparseFeaturesDataset(Dataset):
    def __init__(self, features, targets):
        self.features = features
        self.targets = targets

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self, idx):
        cur_features = torch.from_numpy(self.features[idx].toarray()[0]).float()
        cur_label = torch.from_numpy(np.asarray(self.targets[idx])).long()
        return cur_features, cur_label

In [22]:
gf = np.arange(2,6).reshape(2,2)
print(gf)
gf[0]

[[2 3]
 [4 5]]


array([2, 3])

In [54]:
 help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [52]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
         return a - b
    else:
         return a + b

vfunc = np.vectorize(myfunc)
vfunc([1, 2, 3, 4], 2)
#array([3, 4, 1, 2])

array([3, 4, 1, 2])

In [ ]:
done!
the right answer :
1.5   -0.5 -0.5  0.8660254 -0.76301256 0.59546695 0.16096788
-0.5 -0.5 -0.5 0.8660254 0.18368219 0.59546695 0.16096788
-0.5 1.5 -0.5 -0.8660254 -0.76301256 0.29382391 1.04243508
-0.5 -0.5 1.5 -0.8660254 1.34234292 -1.4847578 -1.36437084

In [35]:
-float("inf")

-inf

In [87]:
#3.6.6
import numpy as np
x = np.array([[1, 0], 
              [1, 1], 
              [0, 0], 
              [0, 1], 
              [1, 0]])
Kernel = np.array([[1,1, 0], 
                   [0,1,1]])
  
y = [0,0,0]
pos = 0
for k in range(3):  
    print(y)
    for ic in range (2):
        y[k]+=x[pos+k,ic]*Kernel[ic,k]
print(y)    


[0, 0, 0]
[1, 0, 0]
[1, 2, 0]
[1, 2, 0]


In [86]:
import numpy as np
x = np.array([[1, 0], 
              [1, 1], 
              [0, 0], 
              [0, 1], 
              [1, 0]])
# Kernel = np.array([ [1,1,0], 
#                     [0,1,1]])
Kernel = np.array([ [0,1,1], 
                     [1,1,0]])
kt = Kernel.T
print(kt)
y =w = [0,0,0]
#pos = 1
for pos in range(3):# 3 <- Kernel.shape[1]
    #for k in range(3):  

    c = np.multiply(x[pos:pos+3,:],kt)
    print("x[pos:pos+3,:]",x[pos:pos+3,:])
    print(c)
    y = np.sum(c, axis = 1)
    print(y)
    w +=y 
#         for ic in range (2):
#             y[k]+=x[pos+k,ic]*Kernel[ic,k]
#print(y)    
print(w)

[[0 1]
 [1 1]
 [1 0]]
x[pos:pos+3,:] [[1 0]
 [1 1]
 [0 0]]
[[0 0]
 [1 1]
 [0 0]]
[0 2 0]
x[pos:pos+3,:] [[1 1]
 [0 0]
 [0 1]]
[[0 1]
 [0 0]
 [0 0]]
[1 0 0]
x[pos:pos+3,:] [[0 0]
 [0 1]
 [1 0]]
[[0 0]
 [0 1]
 [1 0]]
[0 1 1]
[1 3 1]


In [66]:
Kernel.shape[1]


3

In [84]:
x = np.array([[1, 0], 
              [1, 1], 
              [0, 0],] 
              )
Kernel = np.array([ [1,1,0], 
                    [0,1,1]])
x.dot(Kernel)

array([[1, 1, 0],
       [1, 2, 1],
       [0, 0, 0]])

In [88]:
#done!
import numpy as np
x = np.array([[1, 0], 
              [1, 1], 
              [0, 0], 
              [0, 1], 
              [1, 0]])
Kernel = np.array([[1,1, 0], 
                   [0,1,1]])
  
y = [0,0,0]
pos = 0
for pos in range(3):
    for k in range(3):  
        print(y[pos])
        for ic in range (2):
            y[pos]+=x[pos+k,ic]*Kernel[ic,k]
print(y) 

0
1
3
0
1
1
0
0
1
[3, 2, 1]


In [89]:
#3.6.7 done!
import numpy as np
x = np.array([[1, 0], 
              [1, 1], 
              [0, 0], 
              [0, 1], 
              [1, 0]])
Kernel = np.array([[[1,1, 0], 
                   [0,1,1]],
                  [[1,0, 0], 
                   [0,0,1]]])
  
y = [[0,0],
     [0,0],
     [0,0]]
pos = 0
for pos in range(3):
    for j in range(2):  
        print(y[pos][j])
        for k in range(3):
            for ic in range (2):
                y[pos][j]+=x[pos+k,ic]*Kernel[j,ic,k]
print(y) 

0
0
0
0
0
0
[[3, 1], [2, 2], [1, 0]]


In [2]:
#4.5.3
import numpy as np
W = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])
W.T
a = W.dot(W.T)
print(a)

[[1 0 1 0]
 [0 1 1 0]
 [1 1 2 0]
 [0 0 0 0]]


In [ ]:
!pip install tensorflow


In [4]:
#https://overcoder.net/q/39323/%D0%BA%D0%B0%D0%BA-%D1%80%D0%B5%D0%B0%D0%BB%D0%B8%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D1%84%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8E-softmax-%D0%B2-python
import tensorflow.compat.v1 as tf
#import tensorflow as tf
import numpy as np
batch = np.asarray(a)
x = tf.placeholder(tf.float32, shape=[None, 4])
y = tf.nn.softmax(x)
init = tf.initialize_all_variables()
sess = tf.Session()
sess.run(y, feed_dict={x: batch})

RuntimeError: tf.placeholder() is not compatible with eager execution.

In [17]:
import numpy as np
W = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])
W.T
a = W.dot(W.T)
print(a)


[[1 0 1 0]
 [0 1 1 0]
 [1 1 2 0]
 [0 0 0 0]]


In [9]:
at = a.T
def softmax(x):
   return np.exp(x)/sum(np.exp(x))


np.transpose(softmax(a))


array([[0.36552929, 0.13447071, 0.36552929, 0.13447071],
       [0.13447071, 0.36552929, 0.36552929, 0.13447071],
       [0.19661193, 0.19661193, 0.53444665, 0.07232949],
       [0.25      , 0.25      , 0.25      , 0.25      ]])

In [4]:
#!pip install torch
#!pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-win_amd64.whl
#!pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
!pip install torch===1.5.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [23]:
import torch
sm_rows = torch.nn.Softmax(dim = 1)
c= sm_rows(torch.from_numpy(a).type(torch.FloatTensor))
print(c)
#x = x.type(torch.FloatTensor)

tensor([[0.3655, 0.1345, 0.3655, 0.1345],
        [0.1345, 0.3655, 0.3655, 0.1345],
        [0.1966, 0.1966, 0.5344, 0.0723],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [25]:
s = torch.from_numpy(W).type(torch.FloatTensor)
s

tensor([[1., 0.],
        [0., 1.],
        [1., 1.],
        [0., 0.]])

In [26]:
#4.5.5 done!
r = torch.mm(c,s)
r

tensor([[0.7311, 0.5000],
        [0.5000, 0.7311],
        [0.7311, 0.7311],
        [0.5000, 0.5000]])

In [ ]:
# import os 
# os.add_dll_directory("E:\Docs\python\WPy64-3800\python-3.8.0.amd64\lib\site-packages\torch\lib\")

In [7]:
!pip install torch===1.5.0 torchvision===0.6.0 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html


In [ ]:
!pip uninstall torch

In [1]:
!pip check


spyder 3.3.6 requires pyqt5, which is not installed.
pyqtwebengine 5.13.1 requires pyqt5, which is not installed.
uvicorn 0.9.0 has requirement h11==0.8.*, but you have h11 0.9.0.
spyder 3.3.6 has requirement pyqtwebengine<5.13; python_version >= "3", but you have pyqtwebengine 5.13.1.


In [2]:
!pip show torch

In [5]:
!pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
  Using cached https://download.pytorch.org/whl/cpu/torch-1.4.0%2Bcpu-cp38-cp38-win_amd64.whl (77.4 MB)


In [54]:
#2.5.7 done
import numpy as np
from scipy.special import softmax

Input = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])
Input.T
a = Input.dot(Input.T)
print(a)

# def softmax(x):
#    return np.exp(x)/sum(np.exp(x))


ProjK = np.array([[1, 0], [0, 1]])
ProjQ = np.array([[0, 0], [1, 0]])
ProjV = np.array([[1, 0], [0, 1]])
BiasK = np.array([0,0])
BiasQ = np.array([0,0])
BiasV = np.array([0,0])
#Keys=Input⋅ProjK+BiasK
#Queries=Input⋅ProjQ+BiasQQueries = Input \cdot Proj_Q + Bias_QQueries=Input⋅ProjQ​+BiasQ​
#Values=Input⋅ProjV+BiasVValues = Input \cdot Proj_V + Bias_VValues=Input⋅ProjV​+BiasV​
#Logits=Queries⋅Keys.T
#AttScores=softmax(Logits,rows)
#Result=AttScores⋅Values
Keys = Input.dot(ProjK)+BiasK
print(Input.dot(ProjK))
print("Keys\n",Keys)
Queries = Input.dot(ProjQ)+BiasQ
print("Queries\n",Queries)
Values = Input.dot(ProjV)+BiasV
print("Values\n",Values)
Logits=Queries.dot(Keys.T)
print("Logits\n",Logits)
AttScores=softmax(Logits, axis = 1)
print("Logits\n",Logits)
Result=AttScores.dot(Values)
print("Result\n",Result)

[[1 0 1 0]
 [0 1 1 0]
 [1 1 2 0]
 [0 0 0 0]]
[[1 0]
 [0 1]
 [1 1]
 [0 0]]
Keys
 [[1 0]
 [0 1]
 [1 1]
 [0 0]]
Queries
 [[0 0]
 [1 0]
 [1 0]
 [0 0]]
Values
 [[1 0]
 [0 1]
 [1 1]
 [0 0]]
Logits
 [[0 0 0 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 0 0 0]]
Logits
 [[0 0 0 0]
 [1 0 1 0]
 [1 0 1 0]
 [0 0 0 0]]
Result
 [[0.5        0.5       ]
 [0.73105858 0.5       ]
 [0.73105858 0.5       ]
 [0.5        0.5       ]]


In [48]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)
# array([[0.36552929, 0.13447071, 0.19661193, 0.25      ],
#        [0.13447071, 0.36552929, 0.19661193, 0.25      ],
#        [0.36552929, 0.36552929, 0.53444665, 0.25      ],
#        [0.13447071, 0.13447071, 0.07232949, 0.25      ]])

# def softmax(x):
#     e_x = np.exp(x - np.max(x))
#     return e_x / e_x.sum()
# array([[0.08313107, 0.03058221, 0.08313107, 0.03058221],
#        [0.03058221, 0.08313107, 0.08313107, 0.03058221],
#        [0.08313107, 0.08313107, 0.22597368, 0.03058221],
#        [0.03058221, 0.03058221, 0.03058221, 0.03058221]])



softmax(a)

array([[0.36552929, 0.13447071, 0.19661193, 0.25      ],
       [0.13447071, 0.36552929, 0.19661193, 0.25      ],
       [0.36552929, 0.36552929, 0.53444665, 0.25      ],
       [0.13447071, 0.13447071, 0.07232949, 0.25      ]])

In [32]:
a

array([[1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 1, 2, 0],
       [0, 0, 0, 0]])

In [38]:
np.sum(a, axis=0)

array([2, 2, 4, 0])

In [34]:
sum(np.exp(a))

array([ 7.43656366,  7.43656366, 13.82561976,  4.        ])

In [53]:
from scipy.special import softmax
m = softmax(a)
print(m,end = "\n")
m0 = softmax(a, axis=0)
print(m0,end = "\n")
m1 = softmax(a, axis=1)
print(m1,end = "\n")

[[0.08313107 0.03058221 0.08313107 0.03058221]
 [0.03058221 0.08313107 0.08313107 0.03058221]
 [0.08313107 0.08313107 0.22597368 0.03058221]
 [0.03058221 0.03058221 0.03058221 0.03058221]]
[[0.36552929 0.13447071 0.19661193 0.25      ]
 [0.13447071 0.36552929 0.19661193 0.25      ]
 [0.36552929 0.36552929 0.53444665 0.25      ]
 [0.13447071 0.13447071 0.07232949 0.25      ]]
[[0.36552929 0.13447071 0.36552929 0.13447071]
 [0.13447071 0.36552929 0.36552929 0.13447071]
 [0.19661193 0.19661193 0.53444665 0.07232949]
 [0.25       0.25       0.25       0.25      ]]


In [113]:
#4.5.9 done!
import numpy as np
from scipy.special import softmax

Input = np.array([[1, 0], [0, 1], [1, 1], [0, 0]])
Input.T
a = Input.dot(Input.T)
print(a)

# def softmax(x):
#    return np.exp(x)/sum(np.exp(x))


ProjK = np.array([[[1, 0], [0, 0]],
                  [[0, 0], [1, 0]]])
ProjQ = np.array([[[0, 1], [1, 1]],
                  [[1, 0], [1, 1]]])
ProjV = np.array([[1, 0],
                  [0, 1]])
BiasK = np.array([0,0])
BiasQ = np.array([0,0])
BiasV = np.array([0])
#Keys=Input⋅ProjK+BiasK
#Queries=Input⋅ProjQ+BiasQQueries = Input \cdot Proj_Q + Bias_QQueries=Input⋅ProjQ​+BiasQ​
#Values=Input⋅ProjV+BiasVValues = Input \cdot Proj_V + Bias_VValues=Input⋅ProjV​+BiasV​
#Logits=Queries⋅Keys.T
#AttScores=softmax(Logits,rows)
#Result=AttScores⋅Values
Keys = np.zeros((2,4,2))
Queries = np.zeros((2,4,2))
Values = np.zeros((2,4))
AttScores = np.zeros((2,4,4))
Logits = np.zeros((2,4,4))
Result = np.zeros((2,4))
for j in range(2):
    print("ProjK[j]",ProjK[j],np.shape(ProjK[j]),np.shape(ProjK))
    Keys[j] = Input.dot(ProjK[j])+BiasK
    print(Input.dot(ProjK[j]))
    print("Keys\n",Keys[j])
    Queries[j] = Input.dot(ProjQ[j])+BiasQ
    print("Queries\n",Queries[j])
    Values[j] = Input.dot(ProjV[j])+BiasV
    print("Values\n",Values[j])
    Logits[j] =  Queries[j].dot(Keys[j].T)
    print("Logits\n",Logits[j])
    AttScores[j]=softmax(Logits[j], axis = 1)
    print("AttScores\n",Logits[j])
    Result[j]=AttScores[j].dot(Values[j])
    print("Result\n",Result[j])
d = np.stack((Result[0],Result[1]))
print(d)
print(d.T)

[[1 0 1 0]
 [0 1 1 0]
 [1 1 2 0]
 [0 0 0 0]]
ProjK[j] [[1 0]
 [0 0]] (2, 2) (2, 2, 2)
[[1 0]
 [0 0]
 [1 0]
 [0 0]]
Keys
 [[1. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]]
Queries
 [[0. 1.]
 [1. 1.]
 [1. 2.]
 [0. 0.]]
Values
 [1. 0. 1. 0.]
Logits
 [[0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]]
AttScores
 [[0. 0. 0. 0.]
 [1. 0. 1. 0.]
 [1. 0. 1. 0.]
 [0. 0. 0. 0.]]
Result
 [0.5        0.73105858 0.73105858 0.5       ]
ProjK[j] [[0 0]
 [1 0]] (2, 2) (2, 2, 2)
[[0 0]
 [1 0]
 [1 0]
 [0 0]]
Keys
 [[0. 0.]
 [1. 0.]
 [1. 0.]
 [0. 0.]]
Queries
 [[1. 0.]
 [1. 1.]
 [2. 1.]
 [0. 0.]]
Values
 [0. 1. 1. 0.]
Logits
 [[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 2. 2. 0.]
 [0. 0. 0. 0.]]
AttScores
 [[0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 2. 2. 0.]
 [0. 0. 0. 0.]]
Result
 [0.73105858 0.73105858 0.88079708 0.5       ]
[[0.5        0.73105858 0.73105858 0.5       ]
 [0.73105858 0.73105858 0.88079708 0.5       ]]
[[0.5        0.73105858]
 [0.73105858 0.73105858]
 [0.73105858 0.88079708]
 [0.5        0.5       ]]
